DELETE http://localhost:8080/events/10
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjEsImVtYWlsIjoidXJtaXRwYXRlbDAxQGdtYWlsLmNvbSIsImV4cCI6MTc4Nzc1NzcwNH0.Mh6Sq_VYCpj5_2KT9YIhIqC_dZiMHeQdXXYRWy81ppA
