POST http://localhost:8080/events/2/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjIsImVtYWlsIjoidXJtaXRwYXRlbDAyQGdtYWlsLmNvbSIsImV4cCI6MTc4ODQxMjI3NH0.XSgMDGkC8_REeV9XHvZi-oqoufn1QjIPWnvqKJGrE5Q
