PUT http://localhost:8080/events/3
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjEsImVtYWlsIjoidXJtaXRwYXRlbDAxQGdtYWlsLmNvbSIsImV4cCI6MTc4Nzc2MzYwMH0.9Im9wVwYpKLLR34rWjWCvWjKjy5muDJISZSq0uJJA6s

{
    "name" : "Updated Test Event 01",
    "description" : "Updated Test Event description",
    "location" : "Updated Test location",
    "datetime" : "2026-08-01T15:00:00.000Z"
}