PUT http://localhost:8080/events/2
content-type: application/json

{
    "name" : "Updated Test Event 01",
    "description" : "Updated Test Event description",
    "location" : "Updated Test location",
    "datetime" : "2026-08-01T15:00:00.000Z"
}