PUT http://localhost:8080/events/10
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjEsImVtYWlsIjoidXJtaXRwYXRlbDAxQGdtYWlsLmNvbSIsImV4cCI6MTc4Nzc1NzcwNH0.Mh6Sq_VYCpj5_2KT9YIhIqC_dZiMHeQdXXYRWy81ppA

{
    "name" : "Updated Test Event 01",
    "description" : "Updated Test Event description",
    "location" : "Updated Test location",
    "datetime" : "2026-08-01T15:00:00.000Z"
}